//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alicja.BankService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankService.IBankService", CallbackContract=typeof(Alicja.BankService.IBankServiceCallback))]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/doInit")]
        void doInit(Common.Banknote aBanknote);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/doCreateAgreement")]
        void doCreateAgreement(string[] aBlindMessages);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/doVerifyAgreement")]
        void doVerifyAgreement(Common.PublicSecret[] aSecrets, string[] aBlindingFactors);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/doCreateSecret")]
        void doCreateSecret(Common.PublicSecret aSecret);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/doVerifySecret")]
        void doVerifySecret(Common.PublicSecret aPublic, Common.PrivateSecret aPrivate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/onInit")]
        void onInit(Common.Banknote aBanknote, int aBanknoteCount, string aPublicKey);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/onCreateAgreement")]
        void onCreateAgreement(int aIndex);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/onVerifyAgreement")]
        void onVerifyAgreement(Common.PublicSecret aBanknote, string aBlindSignature, bool aAgreed);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/doUncoverSecret")]
        void doUncoverSecret(Common.PublicSecret aSecret);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankService/onVerifySecret")]
        void onVerifySecret(Common.PublicSecret aSecret, bool aAgreed);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : Alicja.BankService.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.DuplexClientBase<Alicja.BankService.IBankService>, Alicja.BankService.IBankService {
        
        public BankServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BankServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BankServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void doInit(Common.Banknote aBanknote) {
            base.Channel.doInit(aBanknote);
        }
        
        public void doCreateAgreement(string[] aBlindMessages) {
            base.Channel.doCreateAgreement(aBlindMessages);
        }
        
        public void doVerifyAgreement(Common.PublicSecret[] aSecrets, string[] aBlindingFactors) {
            base.Channel.doVerifyAgreement(aSecrets, aBlindingFactors);
        }
        
        public void doCreateSecret(Common.PublicSecret aSecret) {
            base.Channel.doCreateSecret(aSecret);
        }
        
        public void doVerifySecret(Common.PublicSecret aPublic, Common.PrivateSecret aPrivate) {
            base.Channel.doVerifySecret(aPublic, aPrivate);
        }
    }
}
